# config.yaml: アプリケーションの設定ファイル

model_config:
  # --- デフォルトで選択する数値特徴量 ---
  # 利用可能な全ての数値特徴量をコメントアウトでリストアップ
  # デフォルトで全て選択する場合は null のままにします。
  # 特定の数値特徴量をデフォルトにする場合は、下のコメントを解除して指定します。
  # default_numeric_features: null # null の場合は全ての数値特徴量がデフォルト
  default_numeric_features:
    # - 出発日_価格             # リスト項目をインデント
    # - 利用台数
    # - 日々_価格
    # - 基本料金
    # - 割引
    # - 価格_トヨタ
    # - 価格_オリックス
    # - 曜日
    # - 取消台数
    # - 利用台数累積_lag3
    #- 利用台数累積_lag7
    #- 利用台数累積_lag15
    - 利用台数累積_lag30
    - 価格差
    - 価格比

  # --- デフォルトで選択するカテゴリ特徴量 ---
  # 利用可能な全てのカテゴリ特徴量をコメントアウトでリストアップ
  # デフォルトで選択したいものをコメント解除します。
  default_categorical_features:
    - ja_name      # 現在のデフォルト
    - 車両クラス   # 現在のデフォルト
  #   - 曜日_name
    #   - en_name

  # --- デフォルトで評価するモデル (オプション) ---
  # デフォルトで選択したいモデルをコメント解除します。
  default_models_to_compare:
    - xgboost
    - lightgbm
  #   - lr
  #   - ridge
  #   - lasso
  #   - knn
  #   - dt
  #   - rf
  #   - et
  #   - gbr
  #   - ada 